sudo: required

dist: trusty

language: scala

branches:
  only:
    - master

scala:
   - 2.11.8

jdk:
  - oraclejdk8

before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget https://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - tar -xvf geckodriver-v0.11.1-linux64.tar.gz

script:
   - sbt ++$TRAVIS_SCALA_VERSION test:compile test

addons:
  firefox: 50.0.2
