sudo: false

# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html#%28Experimental%29+Reusing+Ivy+cache
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

# dist: trusty

language: scala

branches:
  only:
    - master

scala:
   - 2.11.8

jdk:
  - oraclejdk8

before_script:
#  - export CHROME_BIN=/usr/bin/google-chrome
#  - sudo apt-get update
#  - sudo apt-get install -y libappindicator1 fonts-liberation
#  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#  - sudo dpkg -i google-chrome*.deb
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
#  - wget https://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip
#  - unzip chromedriver_linux64.zip
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - tar -xvf geckodriver-v0.11.1-linux64.tar.gz

script:
   - sbt ++$TRAVIS_SCALA_VERSION test:compile test

addons:
  firefox: 41.0
